image: gitlab/dind

services: 
  -docker:dind

variables: 
  IMAGE_NAME: chinhnguyenduc/spring_docker

stages:
  - build
  - test
  - docker

maven-build:
    image: maven:3.8.1-openjdk-17-slim
    stage: build
    script: "./mvn clean package"
    artifacts:
      paths:
        - target/*.jar

maven-test: # run unit test của project
  image: maven:3.8.1-openjdk-17-slim
  stage: test
  script: "mvn test"
  artifacts:
    paths:
      - target/*.jar

docker-build: # bước này sẽ build iamge từ Dockerfile và push lên docker hub
  stage: docker
  script:
    - docker login -u $USERNAME_DOCKER -p $PASSWORD_DOCKER # nhập tên username và password docker hub của các bạn ở đây để có quyền push
    - docker build -t $IMAGE_NAME:1.0 . # build image, 1.0 là tag coi nó như version
    - docker push $IMAGE_NAME:1.0 # push image docker hub sau khi build thành công
